AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  S3Bucket:
    Type: String
    Description: S3 Bucket to store the report in
  SlackNotificationToken:
    Type: String
    Description: Slack Token
  ListOfCostTags:
    Type: String
    Description: Comma seperated list of all Cost Allocation Tags
  CurrentMonth:
    Type: String
    Description: true | false for if current partial month included
  DayOfMonth:
    Type: Number
    Default: 6
    Description: DayOfMonth for Schedule, default 6 - use 12 if you want to report
      refunds and finalised Enterprise Support.
Resources:
  CostExplorerReport:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CostExplorerReportLambda
      Description: Function for generating / sending monthly cost report
      MemorySize: 256
      Timeout: 60
      Handler: lambda.main_handler
      Runtime: python3.6
      CodeUri: s3://obp-aws-cost-explorer-712098116579/obp-aws-cost-explorer-report-builds/d8895c228ca9e30f57e7950843f40c4c
      Layers:
      - arn:aws:lambda:us-east-1:712098116579:layer:obp-aws-cost-explorer-report:1
      Role:
        Fn::GetAtt:
        - CostExplorerReportLambdaIAMRole
        - Arn
      Environment:
        Variables:
          S3_BUCKET:
            Ref: S3Bucket
          SlackNotificationToken:
            Ref: SlackNotificationToken
          COST_TAGS:
            Ref: ListOfCostTags
          CURRENT_MONTH:
            Ref: CurrentMonth
          INC_SUPPORT: 'false'
      Events:
        MonthlyEvent:
          Properties:
            Schedule:
              Fn::Sub: cron(0 1 ${DayOfMonth} * ? *)
          Type: Schedule
  CostExplorerReportLambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ce:*
            Resource: '*'
          - Effect: Allow
            Action:
            - organizations:ListAccounts
            Resource: '*'
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:PutObjectAcl
            Resource:
              Fn::Sub: arn:aws:s3:::${S3Bucket}/*
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AllowLambdaServiceToAssumeRole
          Effect: Allow
          Action:
          - sts:AssumeRole
          Principal:
            Service:
            - lambda.amazonaws.com
      PermissionsBoundary:
        Fn::Sub: arn:aws:iam::712098116579:policy/standard-permissions-boundary
